name: "Build individual target"
description: "Build individual target"

inputs:
  target:
    description: "make target to build"
    required: true
  container_token:
    description: "GHCR token"
    required: true
  platforms:
    description: Platforms to build for
    default: linux/arm64,linux/amd64

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.container_token }}
    - shell: bash
      run: |
        set -xe
        docker buildx create --use --platform=${{ inputs.platforms }} --name multi-platform-builder
        docker buildx inspect --bootstrap
        docker buildx install
        make DOCKER_BUILDX_FLAGS="--platform ${{ inputs.platforms }} --push" ${{ inputs.target }}
